# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 590c59b263664229686756d4bf531ca5b13f942e8928c87915ed1c8c44ae1065bdb862023df5b986cd5e663ed7c72cff8761b5359317130b6d9d1f5ec60033b2

test:
  secret_key_base: 08e106b4c454a58c63cfcac680fd128e4c40790e403ad1284d5d01359ac00aa667b95dad3d8e6b68963d701fd87d9ab2cf9dae4328abcc9a51cd2e76394dd572

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
